# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-4Q30BBKXKF'

menu:
- {name: 'Home', path: '', url:  '' }
- {name: 'Archives', path: 'menu', url: 'archives.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/merklol'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/maxim-smolyakov-8945211a5/'}
- {icon: 'envelope', link: 'mailto:sm.maksim@icloud.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
